---

- name: hosts > File
  lineinfile:
    path:   "{{ manala_network_hosts_file }}"
    regexp: "^{{ item.keys()[0]|regex_escape() }}\\s+"
    line:   "{{ item.keys()[0] }} {{ item.values()[0] }}"
    unsafe_writes: true
  with_items: "{{ manala_network_hosts }}"
