---

- name: interfaces_configs > Directory
  file:
    path: "{{ manala_network_interfaces_configs_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: manala_network_interfaces_configs|length

- name: interfaces_configs > Exclusive
  find:
    path: "{{ manala_network_interfaces_configs_dir }}"
    patterns: "*"
  changed_when: false
  register: __manala_network_interfaces_configs_exclusive_find
  when: manala_network_interfaces_configs_exclusive

- name: interfaces_configs > Templates present
  template:
    src: "{{ item.template|default(manala_network_interfaces_configs_template|ternary(
      manala_network_interfaces_configs_template,
      'interfaces_configs/empty.j2')) }}"
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ query(
      'manala_network_interfaces_configs',
      manala_network_interfaces_configs,
      __manala_network_interfaces_configs_exclusive_find.files|default([]),
      manala_network_interfaces_configs_dir,
      wantstate='present'
    )
  }}"
  when: item.content is not defined
  notify:
    - networking restart

- name: interfaces_configs > Contents present
  copy:
    content: "{{ item.content }}"
    dest: "{{ item.file }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ query(
      'manala_network_interfaces_configs',
      manala_network_interfaces_configs,
      __manala_network_interfaces_configs_exclusive_find.files|default([]),
      manala_network_interfaces_configs_dir,
      wantstate='present'
    )
  }}"
  when: item.content is defined

- name: configs > Files absent
  file:
    path: "{{ item.file }}"
    state: absent
  loop: "{{ query(
      'manala_network_interfaces_configs',
      manala_network_interfaces_configs,
      __manala_network_interfaces_configs_exclusive_find.files|default([]),
      manala_network_interfaces_configs_dir,
      wantstate='absent'
    )
  }}"
