---

# Hosts
- import_tasks: hosts.yml
  tags:
    - manala_network

# Resolver
- import_tasks: resolver.yml
  tags:
    - manala_network

# Inerfaces
- import_tasks: interfaces.yml
  tags:
    - manala_network
