---

- name: resolver > Template
  template:
    src:  "{{ manala_network_resolver_template|ternary(manala_network_resolver_template, 'resolver/empty.conf.j2') }}"
    dest: "{{ manala_network_resolver_file }}"
    owner: root
    group: root
    mode: "0644"
  when: (manala_network_resolver_template is not none) or (manala_network_resolver_config|length)
